version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "2905:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
