version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - rokala
    volumes:
      - servervol:/home/serverdata   
    container_name: server
    ports:
      - "8085:8085"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - rokala
    volumes:
      - clientvol:/home/clientdata  
    container_name: client
    ports:
      - "8086:8086"
    depends_on:
      - server

networks:
  rokala:

volumes:
  servervol:
  clientvol:
